---
name: static data

on:
  workflow_dispatch:
#  pull_request:
  # schedule:
    # twice peer week
    # - cron: "0 0 * * 1,4"
  # for now, scheduled, we can enable on push master but not make much sense now
  # push:
  #   branches:
  #     - master

permissions:
  contents: read  #  to fetch code (actions/checkout)

jobs:
  prepare:
    name: Run script
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Install pnpm
        run: |
          npm install --global corepack@latest
          corepack enable
          corepack install
      - name: Fetch dependencies
        run: pnpm install
      - name: Build Packages
        run: pnpm build     
      - name: Build package
        run: pnpm --filter @verdaccio/local-scripts run build
      # - name: Get npmjs downloads
      #   run: pnpm --filter @verdaccio/local-scripts run downloads:npmjs
      # - name: Get docker downloads
      #   run: pnpm --filter @verdaccio/local-scripts run pull:docker
      # - name: Get npmjs monhtly downloads
      #   run: pnpm --filter @verdaccio/local-scripts run downloads:monthly
      # - name: Get npmjs year downloads
      #   run: pnpm --filter @verdaccio/local-scripts run downloads:yearly
      - name: Contributors update
        run: pnpm --filter @verdaccio/local-scripts run contributors:update
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: update addson data
        run: pnpm script:addson
      - name: update translations
        run: pnpm run translations
        env:
          TOKEN: ${{ secrets.CROWDIN_VERDACCIO_API_KEY }}
      - name: format
        run: pnpm format
      - name: Commit & Push changes
        uses: actions-js/push@5a7cbd780d82c0c937b5977586e641b2fd94acc5 # tag=v1.5
        with:
          github_token: ${{ secrets.TOKEN_VERDACCIOBOT_GITHUB }}
          message: "chore: updated static data"
          branch: master
          author_email: verdaccio.npm@gmail.com
          author_name: verdacciobot
